credits/plot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'plot'
urlpatterns = [
    path('view/<int:p_id>', views.view, name='view'),
    path('see/', views.see, name='see'),
    path('rent/', views.rent, name='rent'),
    path('buy/', views.buy, name='buy'),
    path('confirm/<int:p_id>', views.confirm, name='confirm'),
    path('final/<int:p_id>', views.final, name='final'),
    path('cancel/', views.cancel, name='cancel')
    ]

homepage/urls.py
from django.urls import path
from homepage import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name='homepage'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('password_reset/',PasswordResetView.as_view(),name="password_reset"),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password_reset_confirm/',PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('feedback/',views.user_feedback,name="user_feedback"),

    path('profile_view/',views.profile_view,name="profile_view"),

    path('edit_profile/',views.edit_profile,name="edit_profile"),
    path('earn_rent/(?P<value>\s+)',views.earn_rent,name="earn_rent"),
    path('sell_this/(?P<value>\s+)',views.sell_this,name="sell_this"),
    path('remove_this/(?P<value>\s+)',views.remove_this,name="remove_this"),
    path('video_chat/',views.video_chat,name="video_chat"),



]

plot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'plot'
urlpatterns = [
    path('view/<int:p_id>', views.view, name='view'),
    path('see/', views.see, name='see'),
    path('rent/', views.rent, name='rent'),
    path('buy/', views.buy, name='buy'),
    path('confirm/<int:p_id>', views.confirm, name='confirm'),
    path('final/<int:p_id>', views.final, name='final'),
    path('cancel/', views.cancel, name='cancel'),
    path('success/', views.success, name='success')
    ]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('django.contrib.auth.urls')),
    path('br/',include('plot.urls')),
    path('paypal/', include('credits.urls')),
    path('', views.index, name='index'),
    path('homepage/', include('homepage.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('feedback/', views.display_feedback, name='display_feedback'),
    path('shop/', include('shop.urls')),
    path('advertisements/', include('adverisements.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credits/plot/views.py
# Create your views here.
from django.db import connection
from django.contrib.auth.models import User

from credits.models import *
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, DeleteView,
                                  UpdateView)
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import datetime
import random

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

import random




cursor = connection.cursor()


def test(request):
    cursor.execute("SELECT * FROM shops")
    b=cursor.fetchall()
    print(b)
    return HttpResponse(b[0])
def see(request):
    user_name = request.user.username
    print(user_name)
    print('helloworld')

    user_id = User.objects.get(username=request.user.username).pk
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id <>%s """ % (int(user_id)))
    b=cursor.fetchall()
    plots=''
    print(b)
    t_dict = {'t': b,'plots':'rent'}
    return render(request, 'plot/first.html', context=t_dict)
def view(request,p_id=None):
    p=p_id
    if request.method=='POST':
        mode= request.POST.get('mode')
        cost= request.POST.get('cost')
        area = request.POST.get('area')
        cursor.execute("""SELECT floor FROM plot_details WHERE p_id = %s""" % (p))

        a = cursor.fetchone()
        floor = a[0]
        t_dict={'mode':mode,'cost':cost,'area':area,'p_id':p_id,'floor':floor}
        return render(request, 'plot/show.html', context=t_dict)

@login_required(login_url='homepage:user_login')
def confirm(request,p_id=None):
    if request.method=='POST':
        mode= request.POST.get('mode')
        cost= request.POST.get('cost')
        area = request.POST.get('area')
        floor = request.POST.get('floor')
        t_dict={'mode':mode,'cost':cost,'area':area,'p_id':p_id,'floor':floor}
        return render(request, 'plot/confirm.html', context=t_dict)

@login_required(login_url='homepage:user_login')
def final(request,p_id=None):
    print('ffg')
    p=p_id
    cost = request.POST.get('cost')
    i = random.randrange(100, 1000, 3)

    if request.method=='POST':
        if 'BUY' in request.POST:
            print("hihiik")
            cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))
            a = cursor.fetchone()
            a = a[0]
            q=1
            print('grsdgrd')
            user_name = request.user.username
            print(user_name)
            user_id = User.objects.get(username=request.user.username).pk
            print('a='+str(a))
            print(p);print(a);print(cost);
            sql = "INSERT INTO sold_transactions (p_id,a_id,user_id,amount) VALUES (%s,%s,%s,%s)"
            val = (p, a,int(user_id),float(cost))
            cursor.execute(sql, val)
            print('hiiererer')
           # cursor.execute("""SELECT balance FROM plot_details WHERE p_id = %s""" % (p))

            cursor.execute("UPDATE plot_details SET admin_id = %s WHERE p_id=%s " % (user_id,p))
            print('hii')


            balance = {'bal':100}
            return render(request, 'credits/index.html', context=balance)
            '''if b[0] in l:
                query = """ UPDATE plot_details SET admin_id = %s WHERE p_id =%s"""

                data = (b[0], p)
                cursor.execute(query,data)

                cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))

                a = cursor.fetchone()
                a = a[0]
                print(a)
                sql = "INSERT INTO sold_transactions (p_id,a_id,user_id,amount) VALUES (%s,%s,%s,%s)"

                val = (p,a,b[0],float(cost))
                cursor.execute(sql, val)
                print('hiiererer')
                return HttpResponse("You bought the plot")

            else:
                sql = "INSERT INTO admin (name, age,phone_num,a_id,street,city,state) VALUES (%s,%s,%s,%s,%s,%s,%s)"
                val = (b[1],b[2],b[5],b[0],b[6],b[7],b[8])
                cursor.execute(sql, val)
                cursor.execute("UPDATE plot_details SET admin_id=b[0] WHERE p_id=p")
                cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))

                a = cursor.fetchone()
                a = a[0]
                print(a)
                sql = "INSERT INTO sold_transactions (p_id,a_id,user_id,amount) VALUES (%s,%s,%s,%s)"

                val = (p, a, b[0], float(cost))
                cursor.execute(sql, val)

                return HttpResponse("You bought the plot")'''
        elif 'TAKE_FOR_RENT' in request.POST:
            print("hihiik")
            #cursor.execute("SELECT * FROM tenants")
            #b=cursor.fetchall()
            '''l=[]
            for i in b:
                l.append(i[4])'''

            cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))
            a = cursor.fetchone()
            a = a[0]
            user_name = request.user.username
            print(user_name)
            user_id = User.objects.get(username=request.user.username).pk
            date = datetime.date.today()
            date += datetime.timedelta(days=30)
            print(p);print(a);print(id);print(float(cost));print(date);
            sql = "INSERT INTO rent_transactions (p_id,a_id,user_id,monthly_amount,next_due_date,status) VALUES (%s,%s,%s,%s,%s,%s)"
            q='pending'
            #print(b[0])
            val = (p, a,int(user_id), float(cost), date,q)
            cursor.execute(sql, val)
            query = """ UPDATE plot_details SET tenant_id = %s WHERE p_id =%s"""
            data = (int(user_id), p)
            cursor.execute(query, data)


            print('hiiererer')

            balance = {'bal': 100}
            return render(request, 'credits/index.html', context=balance)
            '''if b[0] in l:
                query = """ UPDATE plot_details SET tenant_id = %s WHERE p_id =%s"""

                data = (b[0], p)
                cursor.execute(query,data)

                cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))

                a = cursor.fetchone()
                a=a[0]

                sql = "INSERT INTO rent_transactions (p_id,a_id,user_id,monthly_amnt,next_due_date) VALUES (%s,%s,%s,%s,%s)"

                val = (p,a,b[0],float(cost),'12-01-2020')
                cursor.execute(sql, val)
                print('hiiererer')
                return HttpResponse("You bought the plot for rent")

            else:
                sql = "INSERT INTO tenants (name, age,address,phone_num,t_id) VALUES (%s,%s,%s,%s,%s)"
                val = (b[1], b[2], b[6],b[4],b[0])
                cursor.execute(sql, val)
                query = """ UPDATE plot_details SET tenant_id = %s WHERE p_id =%s"""

                data = (b[0], p)
                cursor.execute(query, data
                cursor.execute("""SELECT admin_id FROM plot_details WHERE p_id = %s""" % (p))

                a = cursor.fetchone()
                a = a[0]

                sql = "INSERT INTO rent_transactions (p_id,a_id,user_id,monthly_amnt,next_due_date) VALUES (%s,%s,%s,%s,%s)"

                val = (p, a, b[0], float(cost), '12-01-2020')
                cursor.execute(sql, val)
                print('hiiererer')
                return HttpResponse("You bought the plot for rent")'''
def rent(request):
    user_name = request.user.username
    print(user_name)
    user_id = User.objects.get(username=request.user.username).pk
    us=int(user_id)
    cursor.execute("""SELECT * FROM plot_details WHERE (admin_id<>%s)  """ % (int(user_id)))
    b=cursor.fetchall()
    plots=''
    print(b)
    t_dict = {'t': b,'plots':'rent'}
    return render(request, 'plot/first.html', context=t_dict)
def buy(request):
    user_name = request.user.username
    print(user_name)
    user_id = User.objects.get(username=request.user.username).pk
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id <>%s""" % (int(user_id)))
    b=cursor.fetchall()
    plots=''
    print(b)
    t_dict = {'t': b,'plots':'buy'}
    return render(request, 'plot/first.html', context=t_dict)
def pay_rent(request):
    balances = AccountBalance.objects.filter(user=request.user)
    print(balances)

    balance = {'bal': balances}
    return render(request, 'credits/index.html', context=balance)
def cancel(request):
    return render(request,'plot/cancel.html')

templates/plot/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

      <!--Import Google Icon Font-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
 <link rel="stylesheet" href="{% static 'plot/css/basic.css' %}">    </head>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-link" href="{% url 'plot:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'plot:logout' %}">Logout</a></li>
                <li><a class="navbar-link" href="{% url 'plot:see' %}">Special</a></li>


                {% else %}
                <li><a class="navbar-link" href="{% url 'plot:user_login' %}">Login</a></li>
                {% endif %}



            </ul>

        </div>
    </nav>
    <div>
        {% block body_block %}
        {% endblock %}

    </div>
</body>
</html>

templates/plot/cancel.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
    <h1>Your payment has been cancelled</h1>
    <h2>Please Login to continue</h2>
{% endblock %}

templates/plot/confirm.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <!--Links for materialize css-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

      <!-- font awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title></title>
  <!--links for fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

  </head>


<body>
 <div>
    <form id="myform" method="POST" action="{% url 'plot:final' p_id=p_id %}">
        {% csrf_token %}
        <h5>Purchase Details</h5>
        <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1" >
        <div class="card-content white-text" >
          <span class="card-title">PLOT</span>
            <p>
                MODE OF EXCHANGE:<input type="text" name="mode" style="border:none;color:white;" value="{{ mode }}" readonly>
            Area:<input type="text" name="area" style="border:none;color:white;" value="{{ area }}" readonly>
            Floor:<input type="text" name="floor" style="border:none;color:white;" value="{{ floor }}" readonly>
            Cost:<input type="text" name="cost" style="border:none;color:white;" value="{{ cost }}" readonly>


            </p>
        </div>
        <div class="card-action">

           {% if mode  == "buy" %}
               <center>
          <a class="waves-effect waves-light btn"><input type="submit" name="BUY" value="MAKE PAYMENT">
          </a></center>
            {% endif %}
        {% if  mode == "rent" %}
               <center>
          <a class="waves-effect waves-light btn"><input type="submit" name="TAKE_FOR_RENT" value="MAKE PAYMENT">
          </a></center>
            {% endif %}
        </div>
      </div>
    </div>
  </div>


    </form>

 </div>
</body>
</html>

templates/plot/first.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}

    <!--Links for materialize css-->
    <!-- Compiled and minified CSS -->


{#        <a class="waves-effect waves-light btn" href="{% url 'plot:see' %}"><button>ALL PLOTS</button></a>#}

        <a class="waves-effect waves-light btn" href="{% url 'plot:rent' %}"><button>PLOTS FOR RENT</button></a>
        <a class="waves-effect waves-light btn" href="{% url 'plot:buy' %}"><button>PLOTS FOR PURCHASE</button></a>
{#{% if plots == "all" %}#}
{#    <h6>ALL PLOTS</h6>#}
{# <div>#}
{#{% for a in t %}#}
{#    <form id="myform" method="POST" action="{% url 'plot:view' p_id=a.0 %}">#}
{#        {% csrf_token %}#}
{# <div class="row">#}
{#    <div class="col s12 m6">#}
{#      <div class="card blue-grey darken-1" >#}
{#        <div class="card-content white-text" >#}
{#          <span class="card-title">{{ a.0 }}</span>#}
{#            <p>#}
{#             Available for:  <input type="text" name="mode" style="border:none;color:white;" value="{{ a.6 }}" readonly>#}
{#            Area:<input type="text" name="area" style="border:none;color:white;" value="{{ a.2 }} sqft" readonly>#}
{#            Floor:<input type="text" name="floor" style="border:none;color:white;" value="{{ a.1 }}" readonly>#}
{#            Cost:<input type="text" name="cost" style="border:none;color:white;" value="{{ a.5 }}" readonly>#}
{##}
{##}
{#            </p>#}
{#        </div>#}
{#        <div class="card-action">#}
{##}
{#           <center>#}
{#          <a class="waves-effect waves-light btn"><input type="submit" value="VIEW">#}
{#          </a></center>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{##}
{##}
{##}
{##}
{##}
{##}
{#</form>#}
{##}
{##}
{#            {% endfor %}#}
{##}
{# </div>#}
{#        {% endif %}#}
 {% if plots == "rent" %}
          <h6>PLOTS AVAILABLE FOR RENT</h6>

 <div>
{% for a in t %}
    {% if a.6 == "rent" %}
    <form id="myform" method="POST" action="{% url 'plot:final' p_id=a.0 %}">
        {% csrf_token %}
 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1" >
        <div class="card-content white-text" >
          <span class="card-title">{{ a.0 }}</span>
            <p>
             Available for:   <input type="text" name="mode" style="border:none;color:white;" value="{{ a.6 }}" readonly>
            Area:<input type="text" name="area" style="border:none;color:white;" value="{{ a.2 }} sqft" readonly>
            Floor:<input type="text" name="floor" style="border:none;color:white;" value="{{ a.1 }}" readonly>
            Cost:<input type="text" name="cost" style="border:none;color:white;" value="{{ a.5 }}" readonly>


            </p>
        </div>
        <div class="card-action">

           <center>
          <a class="waves-effect waves-light btn"><input type="submit" value="TAKE_FOR_RENT" name="TAKE_FOR_RENT">
          </a></center>
        </div>
      </div>
    </div>
  </div>






</form>
{% endif %}

            {% endfor %}

 </div>
        {% endif %}
 {% if plots == "buy" %}
          <h6>PLOTS AVAILABLE FOR PURCHASE</h6>

 <div>
{% for a in t %}
    {% if a.6 == "buy" %}
    <form id="myform" method="POST" action="{% url 'plot:final' p_id=a.0 %}">
        {% csrf_token %}
 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1" >
        <div class="card-content white-text" >
          <span class="card-title">{{ a.0 }}</span>
            <p>
             Available for:   <input type="text" name="mode" style="border:none;color:white;" value="{{ a.6 }}" readonly>
            Area:<input type="text" name="area" style="border:none;color:white;" value="{{ a.2 }} sqft" readonly>
            Floor:<input type="text" name="floor" style="border:none;color:white;" value="{{ a.1 }}" readonly>
            Cost:<input type="text" name="cost" style="border:none;color:white;" value="{{ a.5 }}" readonly>


            </p>
        </div>
        <div class="card-action">

           <center>
          <a class="waves-effect waves-light btn"><input type="submit" value="BUY" name="BUY">
          </a></center>
        </div>
      </div>
    </div>
  </div>






</form>
{% endif %}

            {% endfor %}

 </div>
        {% endif %}

{% endblock %}

templates/plot/index.html
<!DOCTYPE html>
{% extends "plot/base.html" %}
    {% block body_block %}
    <div class="jumbotron">
    <h1>WELCOME TO LEVEL FIVE!  </h1>
    </div>
    {% endblock %}

templates/plot/login.html
<!DOCTYPE html>

    {% block body_block %}
<h1> Please Login </h1>

    <form action="{% url 'plot:user_login' %}"  method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
    </form>
    {% endblock %}
</div>

templates/plot/register.html
<!DOCTYPE html>
{% extends "plot/base.html" %}

    {% block body_block %}
<h1>WELCOME TO INDEX!  </h1>
    {% if registered %}
    <h1>Thank you for registering</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
    {% endblock %}
</div>

templates/plot/show.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <!--Links for materialize css-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

      <!-- font awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title></title>
  <!--links for fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

  </head>



    <body>
 <div>
    <form id="myform" method="POST" action="{% url 'plot:confirm' p_id=p_id %}">
        {% csrf_token %}
        <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1" >
        <div class="card-content white-text" >
          <span class="card-title">PLOT</span>
            <p>
             Available for:<input type="text" name="mode" style="border:none;color:white;" value="{{ mode }}" readonly>
            Area:<input type="text" name="area" style="border:none;color:white;" value="{{ area }} sqft" readonly>
            Floor:<input type="text" name="floor" style="border:none;color:white;" value="{{ floor }}" readonly>
            Cost:<input type="text" name="cost" style="border:none;color:white;" value="{{ cost }}" readonly>


            </p>
        </div>
        <div class="card-action">

           {% if mode  == "buy" %}
               <center>
          <a class="waves-effect waves-light btn"><input type="submit" value="BUY">
          </a></center>
            {% endif %}
        {% if  mode == "rent" %}
               <center>
          <a class="waves-effect waves-light btn"><input type="submit" value="TAKE FOR RENT">
          </a></center>
            {% endif %}
        </div>
      </div>
    </div>
  </div>

        <h4>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</h4>
    </form>

 </div>
    </body>
</html>

templates/plot/success.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
    <h1>Your payment has been successful</h1>
    <h2>Please Login to continue</h2>
{% endblock %}