adverisements/urls.py
from django.urls import path, include
from adverisements import views

app_name = 'advertisements'

urlpatterns = [

    path('create_adv/',views.makeadv,name='create_adv'),
    path('viewadv/<int:adv_id>/',views.viewadv,name='viewadv'),
    path('listadv/',views.listadv,name='listadv')


]

homepage/urls.py
from django.urls import path
from homepage import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name='homepage'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('password_reset/',PasswordResetView.as_view(),name="password_reset"),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password_reset_confirm/',PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('feedback/',views.user_feedback,name="user_feedback"),

    path('profile_view/',views.profile_view,name="profile_view"),

    path('edit_profile/',views.edit_profile,name="edit_profile"),
    path('earn_rent/(?P<value>\s+)',views.earn_rent,name="earn_rent"),
    path('sell_this/(?P<value>\s+)',views.sell_this,name="sell_this"),
    path('remove_this/(?P<value>\s+)',views.remove_this,name="remove_this"),
    path('video_chat/',views.video_chat,name="video_chat"),



]

plot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'plot'
urlpatterns = [
    path('view/<int:p_id>', views.view, name='view'),
    path('see/', views.see, name='see'),
    path('rent/', views.rent, name='rent'),
    path('buy/', views.buy, name='buy'),
    path('confirm/<int:p_id>', views.confirm, name='confirm'),
    path('final/<int:p_id>', views.final, name='final'),
    path('cancel/', views.cancel, name='cancel'),
    path('success/', views.success, name='success')
    ]

shop/urls.py
from django.urls import path, include
from django.conf.urls import url
from shop import views

app_name = 'shop'

urlpatterns = [

    path('create_shop/',views.makeshop,name='create_shop'),
    url(r'listshops/viewshop/(?P<sid>\w+)/$',views.viewshop,name='viewshop'),
    path('listshops/',views.listshops,name='listshops'),
    path('categlistshops/<int:category>/',views.categlistshops,name='categlistshops'),
    path('writereview/<int:sid>/',views.reviewtext,name='writereview'),
    url(r'category/',views.category,name='category')

]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('django.contrib.auth.urls')),
    path('br/',include('plot.urls')),
    path('paypal/', include('credits.urls')),
    path('', views.index, name='index'),
    path('homepage/', include('homepage.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('feedback/', views.display_feedback, name='display_feedback'),
    path('shop/', include('shop.urls')),
    path('advertisements/', include('adverisements.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
class UserProfileInfo(models.Model):

    user=models.OneToOneField(User, on_delete=models.CASCADE)
    bio=models.CharField(max_length=250,default="x")
    city=models.CharField(max_length=80,default="x")
    phone=models.CharField(max_length=250,default=12345)

    user=models.ForeignKey(User,on_delete='PROTECT')


    def __str__(self):
        return self.user.username
class feedback(models.Model):
    name=models.CharField(max_length=250)
    rating=models.CharField(max_length=2)
    text=models.CharField(max_length=250)


    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from homepage.models import UserProfileInfo,feedback
from django.contrib import messages

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    re_password=forms.CharField()
    class Meta():
        model=User
        fields=('username','first_name','last_name','email','password')
    def clean(self):
        all_clean_data=super().clean()
        username=all_clean_data['username']
        email=all_clean_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
class FeedbackForm(forms.ModelForm):
    class Meta():
        model=feedback
        fields=('name','rating','text')

homepage/views.py
from django.shortcuts import render
from homepage.forms import UserForm,FeedbackForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages
from homepage.models import feedback
from django.shortcuts import redirect
from django.db import connection
cursor=connection.cursor()
from homepage.models import UserProfileInfo
from collections import namedtuple
from credits.models import *

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]
def index(request):


    return render(request,'homepage/index.html')

def video_chat(request):
    return render(request,'events/video_chat.html')

def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)

        re_password=request.POST.get('re_password')
        password=request.POST.get('password')
        username=request.POST.get('username')
        email=request.POST.get('email')

        print(password,"\n",re_password)
        if re_password==password:
            if user_form.is_valid():
                user=user_form.save()
                user.set_password(user.password) #hashing the password
                user.save() #save hash password to database
                registered=True
                AccountBalance.objects.create(user=user, balance=100)
                user = authenticate(username=username, password=password)
                id=User.objects.get(username=user.username).pk
                print("going")


            else:
                print("something is fishy")
        else:

            raise forms.ValidationError("Passwords do not match.Please Re_enter them")

            raise forms.ValidationError("Passwords do not match")

    else:
        user_form=UserForm()

    return render(request,'homepage/registration.html',{'user_form':user_form,'registered':registered,})

@login_required
def special(request):
    return HttpResponse("You are logged in dude")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')


        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("someone tried to login and failed")
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'homepage/login.html')
def user_feedback(request):
    if request.method=="POST":
        feedback_form=FeedbackForm(data=request.POST)
        if feedback_form.is_valid():
            feedback=feedback_form.save()
            feedback.save()
            print(feedback_form.cleaned_data['text'])
        return HttpResponseRedirect(reverse('index'))
    return render(request,'homepage/feedback.html')
def display_feedback(request):
    feedbacks=feedback.objects.order_by('-pk')

    sum=0
    count=0
    for i in feedbacks:
        sum=sum+int(i.rating)
        count=count+1
    avg_rating=sum/count

    my_dict={'feedbacks':feedbacks,'avg_rating':avg_rating}
    return render(request,'homepage/display_feedbacks.html',my_dict)

def earn_rent(request,value):
    info_object, created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name=request.user.username
    user_id=User.objects.get(username=request.user.username).pk
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND p_id=%s """ % (user_id,value))
    cost = cursor.fetchone()[5]
    if cost==0:
        cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND p_id=%s """ % (user_id, value))
        area=cursor.fetchone()[2]
        cost=area*125*30
    a='rent'

    cursor.execute("UPDATE plot_details SET Available_for='rent', cost=%s WHERE p_id=%s " % (cost/30,value))


    return redirect('homepage:profile_view')

def sell_this(request,value):
    info_object, created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name=request.user.username
    user_id=User.objects.get(username=request.user.username).pk
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND p_id=%s """ % (user_id,value))
    cost = cursor.fetchone()[5]
    if cost==0:
        cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND p_id=%s """ % (user_id, value))
        area=cursor.fetchone()[2]
        cost=area*125
    a='buy'

    cursor.execute("UPDATE plot_details SET Available_for='buy', cost=%s WHERE p_id=%s " % (cost*30,value))


    return redirect('homepage:profile_view')

def remove_this(request,value):
    info_object, created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name=request.user.username
    user_id=User.objects.get(username=request.user.username).pk
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND p_id=%s """ % (user_id,value))
    cost = cursor.fetchone()[5]

    cursor.execute("UPDATE plot_details SET Available_for='shop', cost=%s WHERE p_id=%s " % (0,value))


    return redirect('homepage:profile_view')




def profile_view(request):

    info_object,created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name = request.user.username
    user_id = User.objects.get(username=request.user.username).pk

    a='shop'
    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND Available_for='buy' """ % (user_id))
    buy=namedtuplefetchall(cursor)




    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND Available_for='rent' """ % (user_id))
    rent=namedtuplefetchall(cursor)


    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND Available_for='shop' """ % (user_id))
    shop=namedtuplefetchall(cursor)

    cursor.execute("""SELECT * FROM plot_details WHERE admin_id=%s AND tenant_id IS NOT NULL  """ % (user_id))
    tenant_plots = namedtuplefetchall(cursor)

    cursor.execute("""SELECT * FROM plot_details WHERE admin_id<>%s AND tenant_id=%s  """ % (user_id,user_id))
    my_rented_plots = namedtuplefetchall(cursor)
    print(my_rented_plots)
    my_dict = {'my_rented_plots': my_rented_plots,'tenant_plots':tenant_plots,'shop':shop,'buy':buy,'rent':rent,'user': user_name,  'bio': info_object.bio, 'phone': info_object.phone,'city': info_object.city}
    return render(request,'homepage/user_profile.html', my_dict)

def edit_profile(request):
    if request.method=="POST":
        bio=request.POST.get('bio')
        phone=request.POST.get('phone')
        city=request.POST.get('city')
        user=request.user
        info_object,created=UserProfileInfo.objects.get_or_create(user=user)
        info_object.bio=bio
        info_object.phone=phone
        info_object.city=city
        info_object.save()

        user_name = request.user.username
        print(user_name)

        my_dict = {'user': user_name, 'bio':info_object.bio,'phone':info_object.phone,'city':info_object.city}
        return render(request, 'homepage/user_profile.html', my_dict)
    return render(request,'homepage/edit_profile.html')

templates/homepage/base.html
{#{% load staticfiles %}#}
{#<!DOCTYPE html>#}
{#<html lang="en" dir="ltr">#}
{#  <head>#}
{##}
{#    <!--Links for materialize css-->#}
{#    <!-- Compiled and minified CSS -->#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">#}
{##}
{#      <!-- font awesome -->#}
{#      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">#}
{##}
{#    <!--Import Google Icon Font-->#}
{#    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">#}
{#    <!--Let browser know website is optimized for mobile-->#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>#}
{#    <title></title>#}
{#  <!--links for fonts-->#}
{#  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">#}
{#  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">#}
{#   <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">#}
{##}
{#  </head>#}
{#  <body style="font-family: 'Poppins', sans-serif;">#}
{##}
{#      <div class="navbar-fixed">#}
{#        <nav class="nav-wrapper transparent blue-grey darken-3">#}
{#          <div class="container">#}
{#            <a href="{%url 'index' %}" class="brand-logo" style="font-family: 'Montserrat', sans-serif;">Free Stock</a>#}
{#            <a href="#" class="sidenav-trigger" data-target="mobile-links">#}
{#              <i class="material-icons">menu</i>#}
{#            </a>#}
{##}
{#            <ul class="right hide-on-med-and-down valign-wrapper">#}
{##}
{##}
{##}
{#              {% if request.user.is_authenticated %}#}
{##}
{##}
{#              <li>#}
{#                <a href="{% url 'homepage:video_chat' %}" target="_blank">video chat</a>#}
{#              </li>#}
{#                  <li>#}
{#                <a href="{% url 'homepage:profile_view' %}" >Profile</a>#}
{#              </li>#}
{#              <li>#}
{#                <a href="{% url 'logout' %}" >Logout</a>#}
{#              </li>#}
{#              {% else %}#}
{#              <li>#}
{#                <a href="{% url 'homepage:user_login' %}">Login</a>#}
{#              </li>#}
{##}
{#              <li>#}
{#                  <a href="{% url 'homepage:register' %}">Signup</a>#}
{#              </li>#}
{##}
{#              {% endif %}#}
{##}
{##}
{##}
{#              <li>#}
{#                <a href="#about">About</a>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </nav>#}
{#      </div>#}
{##}
{#      <ul class="sidenav" id="mobile-links">#}
{##}
{##}
{##}
{#        {% if request.user.is_authenticated %}#}
{#        <li>#}
{#          <a href="{ % url 'homepage:profile_view' % }" >Profile</a>#}
{##}
{#        </li>#}
{#        <li>#}
{#          <a href="{% url 'logout' %}" >Logout</a>#}
{#        </li>#}
{#        {% else %}#}
{#        <li>#}
{#          <a href="{% url 'homepage:user_login' %}">Login</a>#}
{#        </li>#}
{#        <li>#}
{#          <a href="{% url 'homepage:register' %}">Signup</a>#}
{#        </li>#}
{#        {% endif %}#}
{##}
{#        <li>#}
{#          <a href="#about" >About</a>#}
{#        </li>#}
{##}
{#      </ul>#}
{##}
{##}
{##}
{##}
{##}
{#      <!-- Compiled and minified JavaScript -->#}
{#      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>#}
{#      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>#}
{#      <script>#}
{#        $(document).ready(function(){#}
{#          $('.sidenav').sidenav();#}
{#          $('.scrollspy').scrollSpy();#}
{#        });#}
{#      </script>#}
{##}
{##}
{##}
{##}
{##}
{#      <div >#}
{#        {% block content %}#}
{#        {% endblock %}#}
{#      </div>#}
{##}
{#              <footer class="page-footer scrollspy blue-grey darken-4" id="about">#}
{#                <div class="container ">#}
{#                  <div class="row">#}
{#                    <div class="col l6 s12">#}
{#                      <h5 class="white-text">About</h5>#}
{##}
{#                      <p class="grey-text text-lighten-4">FreeStock.com is a website where a user can download free stock photos. <br><br>#}
{##}
{#                      <p class="grey-text text-lighten-4">FreeStock.com is a website where a user can download free stock photos <br>#}
{##}
{#                        A user can also join our community by signing up and posting their photographs.This is how our site works.#}
{#                      </p>#}
{#                    </div>#}
{#                    <div class="col l4 offset-l2 s12">#}
{#                      <h5 class="white-text">Contact</h5>#}
{#                      <ul>#}
{##}
{#                        <li><a class="white-text text-ighten-3" href="#!">Gmail</a></li>#}
{#                        <li><a class="white-text text-lighten-3" href="#!">Facebook</a></li>#}
{#                        <li><a class="white-text text-lighten-3" href="#!">Instagram</a></li>#}
{#                        <li><a class="white-text text-lighten-3" href="{% url 'homepage:user_feedback' %}">Feedback</a></li>#}
{#                      </ul>#}
{#                    </div>#}
{#                  </div>#}
{#                  <div class="footer-copyright">#}
{#                    <div class="container">#}
{#                    © 2018 FreeStock.Com#}
{#                    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>#}
{#                    </div>#}
{#                  </div>#}
{#                </div>#}
{#              </footer>#}
{##}
{#  </body>#}
{#</html>#}


{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <!--Links for materialize css-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

      <!-- font awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>GVK Mall</title>
  <!--links for fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

  </head>
  <body style="font-family: 'Poppins', sans-serif;">

      <div class="navbar-fixed">
        <nav class="nav-wrapper transparent blue-grey darken-3">
          <div class="container">
            <a href="{%url 'index' %}" class="brand-logo" style="font-family: 'Montserrat', sans-serif;">GVK Mall</a>
            <a href="#" class="sidenav-trigger" data-target="mobile-links">
              <i class="material-icons">menu</i>
            </a>

            <ul class="right hide-on-med-and-down valign-wrapper">




              {% if request.user.is_authenticated %}

                  <li>
                <a href="{% url 'homepage:profile_view' %}" >Profile</a>
              </li>
              <li>
                <a href="{% url 'plot:see' %}" target="_blank">Buy/Rent</a>
              </li>
                   <li>
                <a href="{% url 'shop:category' %}" target="_blank">Our partners</a>
              </li>
                  <li>
                <a href="{% url 'advertisements:listadv' %}" target="_blank">Offers</a>
              </li>
              <li>
                <a href="{% url 'homepage:video_chat' %}" target="_blank">video chat</a>

              <li>
                <a href="{% url 'logout' %}" >Logout</a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'homepage:user_login' %}">Login</a>
              </li>

              <li>
                  <a href="{% url 'homepage:register' %}">Signup</a>
              </li>

              {% endif %}

                <li>
                <a href="{% url 'shop:category' %}" target="_blank">Our partners</a>
              </li>

              <li>
                <a href="#about">About</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>

      <ul class="sidenav" id="mobile-links">



        {% if request.user.is_authenticated %}
        <li>
          <a href="{ % url 'homepage:profile_view' % }" >Profile</a>

        </li>
                       <li>
                <a href="{% url 'plot:see' %}" target="_blank">Buy/Rent</a>
              </li>

                  <li>
                <a href="{% url 'advertisements:listadv' %}" target="_blank">Offers</a>
              </li>
              <li>
                <a href="{% url 'homepage:video_chat' %}" target="_blank">video chat</a>

              <li>
        <li>
          <a href="{% url 'logout' %}" >Logout</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'homepage:user_login' %}">Login</a>
        </li>
        <li>
          <a href="{% url 'homepage:register' %}">Signup</a>
        </li>
        {% endif %}


              <li>
                <a href="#about">About</a>
              </li>


      </ul>





      <!-- Compiled and minified JavaScript -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
      <script>
        $(document).ready(function(){
          $('.sidenav').sidenav();
          $('.scrollspy').scrollSpy();
        });
      </script>





      <div >
        {% block content %}
        {% endblock %}
      </div>

              <footer class="page-footer scrollspy blue-grey darken-4" id="about">
                <div class="container ">
                  <div class="row">
                    <div class="col l6 s12">
                      <h5 class="white-text">About</h5>

                      <p class="grey-text text-lighten-4">GVK Mall is four floors of exterme fun and enjoyment for all ages <br><br>

                      <p class="grey-text text-lighten-4">Rated as the best mall in South India by Forbes <br>
                        Explore our mall. Anyone can sign up. Login to buy, sell, rent plots. With thousands of daily visitors you can advertise with us for exposure.
                      </p>
                    </div>
                    <div class="col l4 offset-l2 s12">
                      <h5 class="white-text">Contact</h5>
                      <ul>

                        <li><a class="white-text text-ighten-3" href="#!">Gmail</a></li>
                        <li><a class="white-text text-lighten-3" href="#!">Facebook</a></li>
                        <li><a class="white-text text-lighten-3" href="#!">Instagram</a></li>
                        <li><a class="white-text text-lighten-3" href="{% url 'homepage:user_feedback' %}">Feedback</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="footer-copyright">
                    <div class="container">
                    ©ApolloMall SriCity
                    </div>
                  </div>
                </div>
              </footer>

  </body>
</html>

templates/homepage/display_feedbacks.html
{% extends "homepage/base.html" %}
{% block content %}

        <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Total Rating : {{ avg_rating }} / 10</span>
          </div>
        </div>
      </div>
    </div>

<ol>
  {% for item in feedbacks %}

    <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">{{item.name}}:{{item.rating}}</span>
            <p>{{item.text}}</p>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</ol>

<ol>



{% load staticfiles %}

{% endblock %}

templates/homepage/edit_profile.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:edit_profile' %}" name="user_feedback" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="city" type="text" class="validate" name="city" required>
      <label for="city">City</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="phone" type="number" class="validate" name="phone" min="1" max="9999999999" required>
      <label for="phone">Contact Number</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s5 offset-s4">
    <textarea name="bio" rows="8" cols="80"></textarea>
      <label for="bio">Your Bio</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>
{% endblock %}

templates/homepage/feedback.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:user_feedback' %}" name="user_feedback" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="name" type="text" class="validate" name="name" required>
      <label for="name">Name</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="rating" type="number" class="validate" name="rating" min="1" max="10" required>
      <label for="rating">Rating out of 10</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s5 offset-s4">
    <textarea name="text" rows="8" cols="80"></textarea>
      <label for="text">Your Review</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>
{% endblock %}

templates/homepage/login.html
{% extends 'homepage/base.html' %}
{% block content %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:user_login' %}" name="user_login" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="username" type="text" class="validate" name="username" required>
      <label for="username">User Name</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="password" type="password" class="validate" name="password" required>
      <label for="password">Password</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s2 offset-s5">
      <a href="{% url 'homepage:password_reset' %}">Forgot Password?</a>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>



{% endblock %}