plot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'plot'
urlpatterns = [
    path('view/<int:p_id>', views.view, name='view'),
    path('see/', views.see, name='see'),
    path('rent/', views.rent, name='rent'),
    path('buy/', views.buy, name='buy'),
    path('confirm/<int:p_id>', views.confirm, name='confirm'),
    path('final/<int:p_id>', views.final, name='final'),
    path('cancel/', views.cancel, name='cancel'),
    path('success/', views.success, name='success')
    ]

shop/urls.py
from django.urls import path, include
from django.conf.urls import url
from shop import views

app_name = 'shop'

urlpatterns = [

    path('create_shop/',views.makeshop,name='create_shop'),
    url(r'listshops/viewshop/(?P<sid>\w+)/$',views.viewshop,name='viewshop'),
    path('listshops/',views.listshops,name='listshops'),
    path('categlistshops/<int:category>/',views.categlistshops,name='categlistshops'),
    path('writereview/<int:sid>/',views.reviewtext,name='writereview'),
    url(r'category/',views.category,name='category')

]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('django.contrib.auth.urls')),
    path('br/',include('plot.urls')),
    path('paypal/', include('credits.urls')),
    path('', views.index, name='index'),
    path('homepage/', include('homepage.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('feedback/', views.display_feedback, name='display_feedback'),
    path('shop/', include('shop.urls')),
    path('advertisements/', include('adverisements.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class Document(models.Model):
    image = models.FileField(upload_to='documents/')

shop/forms.py
from django import forms
from django.db import models
from shop.models import Document

class ShopAdd(forms.Form):
    sname = forms.CharField()
    a_id=forms.IntegerField()
    open_time=forms.CharField()
    close_time = forms.CharField()
    Registered_for=forms.IntegerField()
    tid=forms.IntegerField()
    owner_name=forms.CharField()
    tenant_name = forms.CharField()
    floor = forms.IntegerField()
    Description=forms.CharField()

class writereview(forms.Form):
    review = forms.CharField()
    name = forms.CharField()

shop/views.py
from django.shortcuts import render
from django.db import connection
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.conf import settings

from shop.forms import ShopAdd,writereview
from django.db import connection
import os.path
import os
import random
import io
import base64
from PIL import Image
from django.core.files.storage import FileSystemStorage




mycursor = connection.cursor()

print('f')

def write_file(data, filename):
    # Convert binary data to proper format and write it on Hard Disk
    with open(filename, 'wb') as file:
        file.write(data)


def makeshop(request):
    sid = random.randrange(100, 500, 3)
    print('a')
    if request.method =='POST':
        print('b')
        if 'proof' in request.FILES and request.POST:
            os.remove(os.path.join(settings.MEDIA_ROOT,'shop/images/img.png'))
            image = request.FILES['proof']
            fs_img = FileSystemStorage(
                location=settings.FS_IMAGE_UPLOADS,
                base_url=settings.FS_IMAGE_URL
            )
            imageName = fs_img.save(image.name, image)

        form = ShopAdd(request.POST)

        if form.is_valid():
            print('c')
            sname = request.POST.get('sname')
            a_id = request.POST.get('a_id')
            open_time = request.POST.get('open_time')
            close_time = request.POST.get('close_time')
            expiry = request.POST.get('Registered_for')
            t_id= request.POST.get('tid')
            owner_name = request.POST.get('owner_name')
            tenant_name = request.POST.get('tenant_name')
            floor = request.POST.get('floor')
            description=request.POST.get('Description')
            category=request.POST.get('category')

            integer=int(close_time)
            if (integer>12):
                integer=integer-12

            close_time=str(integer)
            img = Image.open("media/shop/images/img.png", mode='r')
            imgByteArr = io.BytesIO()
            img.save(imgByteArr, format='PNG')
            imgByteArr = imgByteArr.getvalue()



            sql = "INSERT INTO shop (sname,a_id,open_time,close_time,expiry,t_id,owner_name,tenant_name,floor,description,sid,image,category) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            values=(sname,a_id,open_time,close_time,expiry,t_id,owner_name,tenant_name,floor,description,sid,imgByteArr,category)

            mycursor.execute(sql,values)


            return redirect('shop:viewshop',sid=sid)
    else:
        form = ShopAdd()
        return render(request, 'shop/create_shop.html',{'form': form})



def viewshop(request,sid):
    sid=sid
    mycursor.execute("SELECT * FROM shop WHERE sid LIKE %s",[sid])
    a=mycursor.fetchall()
    mycursor.execute("SELECT * FROM reviews WHERE sid LIKE %s", [sid])
    b = mycursor.fetchall()

    file = io.BytesIO(a[0][10])
    img1 = Image.open(file)
    img1.save("shop/static/shop/images/image.png")

    dict = {
        't': a,
        'x':b,
        'y':img1,
    }

    return render(request,'shop/viewshop.html',context=dict)

def listshops(request):
    mycursor.execute("SELECT * FROM shop")
    a = mycursor.fetchall()
    print(a)
    dict = {'t': a}
    img=['shop/static/shop/images/1.png','shop/static/shop/images/2.png','shop/static/shop/images/3.png','shop/static/shop/images/4.png','shop/static/shop/images/5.png','shop/static/shop/images/6.png','shop/static/shop/images/7.png']

    return render(request,'shop/listshops.html', context=dict)

def categlistshops(request,category):
    category=category
    mycursor.execute("SELECT * FROM shop WHERE category LIKE %s",[category])
    a = mycursor.fetchall()
    print(a)
    dict = {'t': a}
    img=['shop/static/shop/images/1.png','shop/static/shop/images/2.png','shop/static/shop/images/3.png','shop/static/shop/images/4.png','shop/static/shop/images/5.png','shop/static/shop/images/6.png','shop/static/shop/images/7.png']

    return render(request,'shop/categlistshops.html', context=dict)

def category(request):
    return render(request,'shop/category.html')


def reviewtext(request,sid):
    shopid = sid
    review_id=random.randrange(200, 500, 3)
    if request.method == 'POST':
        form = writereview(request.POST)
        if form.is_valid():
            content = request.POST.get('review')
            username = request.POST.get('name')
            sql ="INSERT INTO reviews (sid,review,name,review_id) VALUES (%s,%s,%s,%s)"
            values = (shopid,content,username,review_id)

            mycursor.execute(sql, values)
            return redirect('/shop/listshops/viewshop/' + str(sid) + '/')
    else:
        form = writereview()
    return render(request, 'shop/writereview.html', {'form': form})

shop/templates/shop/categlistshops.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}


   {% for a in t %}
    <form id="myform" method="POST" sname=a.0 %}">
        {% csrf_token %}
    <div class="row">
    <div class="col s4 offset-s4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{ a.11 }}</span>
          <p>{{ a.9 }}</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:viewshop" a.0 %}'>About Us</a>
        </div>
      </div>
    </div>
  </div>
        </form>
    {% endfor %}


{% endblock %}

shop/templates/shop/category.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
    <div class="col s4 ">
      <div class="card medium">
        <div class="card-image">
          <img src={% static 'shop/images/apprales.png' %}>

        </div>
        <div class="card-content">
          <p>Get the latest fashion at least prices</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:categlistshops" 4 %}'>Apparels</a>
        </div>
      </div>
    </div>

    <div class="col s4 ">
      <div class="card medium">
        <div class="card-image">
          <img src={% static 'shop/images/games.png' %}>

        </div>
        <div class="card-content">
          <p>Have best fun with your friends</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:categlistshops" 5 %}'>Games</a>
        </div>
      </div>
    </div>

    <div class="col s4 ">
      <div class="card medium">
        <div class="card-image">
          <img src={% static 'shop/images/movie.png' %}>

        </div>
        <div class="card-content">
          <p>Enjoy the best cinematic experience</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:categlistshops" 2 %}'>Movies</a>
        </div>
      </div>
    </div>
  </div>
<div class="row">
    <div class="col s4">
      <div class="card medium">
        <div class="card-image">
          <img src={% static 'shop/images/electronics.png' %}>

        </div>
        <div class="card-content">
          <p>Electronics</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:categlistshops" 3 %}'>Visit Us</a>
        </div>
      </div>
    </div>

    <div class="col s4 ">
      <div class="card medium">
        <div class="card-image">
          <img src={% static 'shop/images/food.png' %}>
        </div>
        <div class="card-content">
          <p>Food</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:categlistshops" 1 %}'>Visit us</a>
        </div>
      </div>
    </div>
  </div>

{%  endblock %}

shop/templates/shop/create_shop.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
        <div class="row">
            <div class="col s5 offset-s3">
               <h2><center><blockquote>Create a shop </blockquote></center></h2>


         <form method="POST" class="col s12" enctype="multipart/form-data">{% csrf_token %}
             {{ form.as_p }}

            <div class = "row">
            <div class="input-field">
             <select class="browser-default" name="category" id="category">
                <option value="1">Food</option>
                 <option  value="2">Movies</option>
                 <option value="3">Electronics</option>
                <option value="4">Apparels</option>
                 <option value="5">Games</option>
            </select>
                <script>
            document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems, options);
            });
        </script>
            </div></div>
             <div class="file-field input-field">
      <div class="btn">
        <span>Image</span>
             <input type="file" name="proof" accept="image/*">
          </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>


            <div class="row">

           <center><button class="btn waves-effect waves-light" type="submit" name="" value="Submit">Add</button></center>
            </div>
         </form>
            </div>
        </div>
        <script>
            $(document).ready(function(){
            $('select').formSelect();});
        </script>
{% endblock %}

shop/templates/shop/created.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
<p>Congrats You made your shop!!!</p>
</body>
</html>

shop/templates/shop/lists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>HELLLLOO</p>
</body>
</html>

shop/templates/shop/listshops.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
   {% for a in t %}
    <form id="myform" method="POST" sname=a.0 %}">
        {% csrf_token %}
    <div class="row">
    <div class="col s4 offset-s4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{ a.11 }}</span>
          <p>{{ a.9 }}</p>
        </div>
        <div class="card-action">
          <a href='{% url "shop:viewshop" a.0 %}'>About Us</a>
        </div>
      </div>
    </div>
  </div>
        </form>
    {% endfor %}
{% endblock %}

shop/templates/shop/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="../../static/shop/css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <title>Title</title>
</head>
<body>
<h1>Pure CSS Star Rating Widget</h1>
<fieldset class="rating">
    <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
    <input type="radio" id="star4half" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
    <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
    <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
    <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
    <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
    <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
    <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
    <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
</fieldset>
</body>
</html>

shop/templates/shop/viewshop.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
    {% for a in t %}
        <div class="row">
        <div class="col s6 offset-s3">
            <div class="card-panel teal lighten-2"><h2>{{ a.11 }}</h2></div>
            <div class="row">
            <div class="col s7">
                <h4> <p class="red-text">About us:</p><p class="flow-text" > {{ a.9 }}</p></h4>
            </div>
            <div class="col s3 ">
            <img style="width:280px;height:195px;" src="{% static 'shop/images/image.png' %}"/></div>
            </div>

                <h5><div class="row">
                        <div class="col s3 red-text">Admin ID:</div>
                    <div class="col s1 ">{{ a.1 }}</div>
                </div></h5>

                <div class="row">
                    <div class="col s4 push-s7"><h4>
                        <div class="row">
                        <div class="col s2 red-text">Opens:</div>
                            <div class="col s3 offset-s3 ">  {{ a.2 }}am </div>
                        </div>
                         <div class="row">
                        <div class="col s2 red-text">
                        Closes:</div>
                             <div class="col s3 offset-s3 ">  {{ a.3 }}pm </div></h4></div>
                <div class="col s6 pull-s4">
                <h5>
                {%  if a.5 != NULL %}
                <div class="row">
                        <div class="col s6 red-text">Tenant ID:</div>
                    <div class="col s1 ">{{ a.5 }}</div> </div>
                {% endif %}
                <div class="row">
                        <div class="col s6 red-text">Floor:</div>
                    <div class="col s1 ">{{ a.8 }}</div></div>
                {%  if a.5 != NULL %}
                <div class="row">
                        <div class="col s6 red-text">Owner name:</div>
                    <div class="col s1 ">{{ a.6 }}</div> </div>
                {% endif %}
                <div class="row">
                        <div class="col s6 red-text">Tenant name:</div>
                    <div class="col s1 ">{{ a.7 }}</div> </div>

                </h5></div>



        </div>

        </div>
        </div>
        <div class="row">
        <div class="col s6 offset-s3">
        <div class="col s6 offset-s9 "><a href='{% url "shop:writereview" a.0 %}'><h5>Write a review</h5></a></div>
    {% endfor %}


    <blockquote><h3>Reviews:</h3></blockquote><br>
    {% for b in x %}
        <div class="col s6 "><h5>{{ b.1 }}</h5></div>

        <div class="col s6 offset-s3 ">by:{{ b.3 }}</div>

    {% endfor %}
            </div>
            </div>


{% endblock %}

shop/templates/shop/writereview.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class = "container" >
    <h1>Review:</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Add</button>

        </form>

</div>
{% endblock %}